# Generated by Django 3.2.5 on 2021-11-19 19:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pdf', '0002_auto_20211022_2304'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='email',
            new_name='Email',
        ),
        migrations.RenameField(
            model_name='profile',
            old_name='school',
            new_name='School',
        ),
    ]
